### PR TITLE
Add next_local_article and previous_local_article

### PR DESCRIPTION
**Pull request by Linuus**
This PR adds two new methods to fetch the previous and next local article.

The tests fail on Travis, but I don't think that's my fault :)

### CODE REVIEW

**Comment by iwarner** [comment]
@Linuus Thanks for this - I have updated the Travis credentials - could you please merge and submit the PR again please.

**Comment by Linuus** [comment]
@iwarner Rebased and force pushed! 👍

**Comment by iwarner** [comment]
@Linuus 

Ok looks promising - thanks

Ok some comments on this

- Name - local - should be locale
- Have you tested this with named blogs and in a multi-blogs scenario

I have just taken this up so getting up to speed also - should get more on this over the weekend and help out more. But if you can look at the wider scenarios then cool

**Comment by Linuus** [comment]
I agree about the name, the reason I chose it was because I tried to be consistent with `BlogData#local_article`. That method should probably be called `articles_by_locale` or something, but that's up to you 😊

I'll change my method to locale though.

**Comment by iwarner** [comment]
Hiya

I have implemented this manually as I sort out some code styling also.

I have called them

article_locale_previous
article_locale_next

Also implemented
articles_by_locale

placed a deprecation notice on the other methods.

Would be great if you can offer further assistance on this extension, for sure there are a lot of locale items that need completing - such as Tag / Calendar templates getting the correct locales.

Many thanks

**Pull request closed without merging**
