### PR TITLE
Added test to demonstrate failure of article without date

### PR DESCRIPTION
**Pull request by dg-ratiodata**
@tdreyno I added a test to demonstrated what I would like to do.

### CODE REVIEW

**Comment by tdreyno** [comment]
Thanks, this will help a lot

**Comment by dg-ratiodata** [comment]
If you can make this possible, that would be great. Today it's a bit annoying if I need to "move" the date forward to change both dates + it's redundant information.

**Comment by iwarner** [comment]
@dg-ratiodata Hiya can you provide some more context on this please - are you wanting to generate these articles through the command line?

**Comment by iwarner** [comment]
I have added the test, but still do not undestand the root issue Thomas did state you can use either or - but maybe have to change the config of the blog somewhat

**Pull request closed without merging**
